'''68. ソート
"dance"というタグを付与されたアーティストの中でレーティングの投票数が多いアーティスト・トップ10を求めよ．
'''

from pymongo import MongoClient

client = MongoClient('localhost', 27017)
db = client['nlp100_database']
collection = db['nlp100_collection']

documents = collection.find(
    filter={'tags.value': 'dance'}).sort([("rating.count", -1)]).limit(10)

for document in documents:
    print(document)

'''
{'_id': ObjectId('5eb625bde78916f7632a6cbb'), 'area': 'United States', 'name': 'Madonna', 'aliases': [], 'tags': [{'count': 1, 'value': 'dance-pop'}, {'count': 1, 'value': 'electropop'}, {'count': 1, 'value': 'tell me'}, {'count': 1, 'value': 'pop and chart'}, {'count': 1, 'value': 'multiple ipi'}, {'count': 1, 'value': 'electronic'}, {'count': 1, 'value': 'américain'}, {'count': 1, 'value': 'usa'}, {'count': 1, 'value': 'singer'}, {'count': 1, 'value': 'chanteur'}, {'count': 1, 'value': 'american'}, {'count': 4, 'value': 'pop'}, {'count': 1, 'value': 'greatest hits'}, {'count': 1, 'value': 'dance'}], 'rating': {'count': 26, 'value': 88}}
{'_id': ObjectId('5eb625a3e78916f763299645'), 'area': 'Iceland', 'name': 'Björk', 'aliases': [{'name': 'Björk Gudmundsdottir', 'sort_name': 'Björk Gudmundsdottir'}, {'name': 'Björk Gudmudsdóttir', 'sort_name': 'Björk Gudmudsdóttir'}, {'name': 'Bj rk', 'sort_name': 'Bj rk'}, {'name': 'BjÃ¶rk', 'sort_name': 'BjÃ¶rk'}, {'name': 'Björk Guðmundsdóttir', 'sort_name': 'Björk Guðmundsdóttir'}, {'name': 'Biork', 'sort_name': 'Biork'}, {'name': 'Bjõrk', 'sort_name': 'Bjõrk'}, {'name': 'Bjørk', 'sort_name': 'Bjørk'}, {'name': 'Bjцrk', 'sort_name': 'Bjцrk'}, {'name': 'Bjork', 'sort_name': 'Bjork'}], 'tags': [{'count': 1, 'value': 'soundtrack'}, {'count': 2, 'value': 'ambient'}, {'count': 1, 'value': 'islande'}, {'count': 1, 'value': 'trip-hop'}, {'count': 1, 'value': '90s'}, {'count': 1, 'value': 'islandais'}, {'count': 1, 'value': '2000'}, {'count': 3, 'value': 'experimental'}, {'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'idm'}, {'count': 1, 'value': 'rock and indie'}, {'count': 1, 'value': '10s'}, {'count': 2, 'value': 'alternative'}, {'count': 7, 'value': 'icelandic'}, {'count': 1, 'value': 'multiple ipi'}, {'count': 1, 'value': 'baroque pop'}, {'count': 2, 'value': 'jazz'}, {'count': 1, 'value': 'pop'}, {'count': 2, 'value': 'electronica'}, {'count': 1, 'value': '00s'}, {'count': 3, 'value': 'electronic'}, {'count': 3, 'value': 'iceland'}, {'count': 1, 'value': 'art pop'}, {'count': 1, 'value': 'progressive pop'}, {'count': 1, 'value': 'a cappella'}, {'count': 1, 'value': 'trip hop'}, {'count': 1, 'value': 'whimsically inclined'}], 'rating': {'count': 23, 'value': 84}}
{'_id': ObjectId('5eb62604e78916f7632cc986'), 'area': 'United Kingdom', 'name': 'The Prodigy', 'aliases': [{'name': 'Prodigy', 'sort_name': 'Prodigy'}, {'name': 'The Prodigy Vs. The Prodigy', 'sort_name': 'The Prodigy Vs. The Prodigy'}], 'tags': [{'count': 6, 'value': 'big beat'}, {'count': 1, 'value': 'english'}, {'count': 3, 'value': 'british'}, {'count': 1, 'value': 'industrial'}, {'count': 1, 'value': 'dance-punk'}, {'count': 2, 'value': 'uk'}, {'count': 2, 'value': 'breakbeat hardcore'}, {'count': 1, 'value': 'electropunk'}, {'count': 1, 'value': 'britannique'}, {'count': 1, 'value': 'electronica'}, {'count': 1, 'value': '2005'}, {'count': 6, 'value': 'electronic'}, {'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'alternative rock'}, {'count': 1, 'value': 'dance and electronica'}, {'count': 1, 'value': 'rave'}, {'count': 2, 'value': 'hardcore'}, {'count': 1, 'value': 'rock'}, {'count': 1, 'value': 'breakbeat'}, {'count': 1, 'value': 'electro'}, {'count': 2, 'value': 'techno'}], 'rating': {'count': 23, 'value': 90}}
{'_id': ObjectId('5eb62609e78916f7632cf32f'), 'area': 'New York', 'name': 'Rihanna', 'aliases': [{'name': '蕾哈娜', 'sort_name': '蕾哈娜'}, {'name': 'Rhianna', 'sort_name': 'Rhianna'}, {'name': 'Riannah', 'sort_name': 'Riannah'}, {'name': 'Robyn Rihanna Fenty', 'sort_name': 'Fenty, Robyn Rihanna'}, {'name': 'Rihanna', 'sort_name': 'Rihanna'}], 'tags': [{'count': 1, 'value': 'rnb'}, {'count': 3, 'value': 'barbadian'}, {'count': 1, 'value': 'pop and chart'}, {'count': 1, 'value': 'r&b'}, {'count': 2, 'value': 'dancehall'}, {'count': 1, 'value': 'reggae'}, {'count': 2, 'value': 'hip hop'}, {'count': 1, 'value': 'dance'}, {'count': 2, 'value': 'dance-pop'}, {'count': 4, 'value': 'pop'}, {'count': 1, 'value': 'barbade'}, {'count': 1, 'value': 'barbadien'}, {'count': 1, 'value': 'contemporary r b'}, {'count': 1, 'value': 'barbados'}, {'count': 1, 'value': 'rehab'}], 'rating': {'count': 15, 'value': 68}}
{'_id': ObjectId('5eb624dae78916f763218953'), 'area': 'United States', 'name': 'Britney Spears', 'aliases': [{'name': 'Bretney Spears', 'sort_name': 'Bretney Spears'}, {'name': 'B. Spears', 'sort_name': 'B. Spears'}, {'name': 'Brittany Spears', 'sort_name': 'Brittany Spears'}, {'name': 'Briteny Spears', 'sort_name': 'Briteny Spears'}, {'name': 'Brittney Spears', 'sort_name': 'Brittney Spears'}, {'name': 'Britney Jean Spears', 'sort_name': 'Spears, Britney Jean'}], 'tags': [{'count': 7, 'value': 'pop'}, {'count': 1, 'value': 'américain'}, {'count': 1, 'value': 'electropop'}, {'count': 1, 'value': 'usa'}, {'count': 1, 'value': 'pop and chart'}, {'count': 1, 'value': 'dance-pop'}, {'count': 1, 'value': 'urban pop'}, {'count': 1, 'value': 'if you seek amy'}, {'count': 1, 'value': 'dance'}, {'count': 2, 'value': 'american'}], 'rating': {'count': 13, 'value': 83}}
{'_id': ObjectId('5eb62609e78916f7632cfb5c'), 'area': 'United States', 'name': 'Maroon 5', 'aliases': [{'name': 'marron 5', 'sort_name': 'marron 5'}, {'name': 'マルーン５', 'sort_name': 'マルーン５'}, {'name': 'Maroon5', 'sort_name': 'Maroon5'}], 'tags': [{'count': 1, 'value': 'rock and indie'}, {'count': 1, 'value': 'slow pop'}, {'count': 1, 'value': 'automod ng'}, {'count': 1, 'value': 'pop'}, {'count': 1, 'value': 'rock'}, {'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'pop/rock'}, {'count': 1, 'value': 'fixme label mess'}], 'rating': {'count': 11, 'value': 60}}
{'_id': ObjectId('5eb62531e78916f763255ef0'), 'area': 'United States', 'name': 'Adam Lambert', 'aliases': [], 'tags': [{'count': 1, 'value': 'vocalist'}, {'count': 1, 'value': 'glam'}, {'count': 1, 'value': 'costume'}, {'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'showman'}, {'count': 1, 'value': 'rock'}, {'count': 1, 'value': 'pop'}, {'count': 1, 'value': 'american idol'}], 'rating': {'count': 7, 'value': 100}}
{'_id': ObjectId('5eb6258ee78916f76328c7ea'), 'area': 'United Kingdom', 'name': 'Fatboy Slim', 'aliases': [{'name': 'ファットボーイ・スリム', 'sort_name': 'ファットボーイ・スリム'}, {'name': 'Fatboy Slim - Because We Can', 'sort_name': 'Fatboy Slim - Because We Can'}, {'name': 'Fatboy Slin', 'sort_name': 'Fatboy Slin'}, {'name': 'Fat Boy Slim', 'sort_name': 'Fat Boy Slim'}], 'tags': [{'count': 1, 'value': 'trip hop'}, {'count': 3, 'value': 'electronic'}, {'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'trip-hop'}, {'count': 1, 'value': 'english'}, {'count': 1, 'value': 'classic pop and rock'}, {'count': 2, 'value': 'uk'}, {'count': 2, 'value': 'big beat'}, {'count': 1, 'value': 'britannique'}, {'count': 3, 'value': 'british'}, {'count': 1, 'value': '1998'}], 'rating': {'count': 7, 'value': 77}}
{'_id': ObjectId('5eb625b1e78916f7632a1330'), 'area': 'United Kingdom', 'name': 'Basement Jaxx', 'aliases': [{'name': 'Basementt Jaxx', 'sort_name': 'Basementt Jaxx'}, {'name': 'Basment Jaxx', 'sort_name': 'Basment Jaxx'}, {'name': 'Basemant Jaxx', 'sort_name': 'Basemant Jaxx'}, {'name': 'Bassment Jaxx', 'sort_name': 'Bassment Jaxx'}, {'name': 'Basement Jazz', 'sort_name': 'Basement Jazz'}, {'name': 'Basements Jaxx', 'sort_name': 'Basements Jaxx'}], 'tags': [{'count': 1, 'value': 'english'}, {'count': 2, 'value': 'uk'}, {'count': 1, 'value': 'house'}, {'count': 1, 'value': 'uk garage'}, {'count': 3, 'value': 'dance'}, {'count': 4, 'value': 'british'}, {'count': 1, 'value': 'dance and electronica'}, {'count': 1, 'value': '10s'}, {'count': 2, 'value': 'electronic'}, {'count': 1, 'value': '00s'}, {'count': 1, 'value': '90s'}], 'rating': {'count': 6, 'value': 83}}
{'_id': ObjectId('5eb625ace78916f76329e10f'), 'area': 'United Kingdom', 'name': 'Cornershop', 'aliases': [{'name': 'Conershop', 'sort_name': 'Conershop'}, {'name': 'Corner Shop -', 'sort_name': 'Corner Shop -'}, {'name': 'Cornership', 'sort_name': 'Cornership'}, {'name': 'Corner Shop', 'sort_name': 'Corner Shop'}], 'tags': [{'count': 1, 'value': 'dance'}, {'count': 1, 'value': 'indie'}, {'count': 1, 'value': 'brit pop'}, {'count': 1, 'value': 'indian'}, {'count': 2, 'value': 'british'}, {'count': 1, 'value': 'uk'}, {'count': 1, 'value': 'asian'}, {'count': 1, 'value': 'british asian'}, {'count': 1, 'value': 'english'}, {'count': 1, 'value': 'rock and indie'}], 'rating': {'count': 5, 'value': 68}}
'''


'''shell
{ "_id" : ObjectId("5eb625bde78916f7632a6cbb"), "area" : "United States", "name" : "Madonna", "aliases" : [ ], "tags" : [ { "count" : 1, "value" : "dance-pop" }, { "count" : 1, "value" : "electropop" }, { "count" : 1, "value" : "tell me" }, { "count" : 1, "value" : "pop and chart" }, { "count" : 1, "value" : "multiple ipi" }, { "count" : 1, "value" : "electronic" }, { "count" : 1, "value" : "américain" }, { "count" : 1, "value" : "usa" }, { "count" : 1, "value" : "singer" }, { "count" : 1, "value" : "chanteur" }, { "count" : 1, "value" : "american" }, { "count" : 4, "value" : "pop" }, { "count" : 1, "value" : "greatest hits" }, { "count" : 1, "value" : "dance" } ], "rating" : { "count" : 26, "value" : 88 } }
{ "_id" : ObjectId("5eb625a3e78916f763299645"), "area" : "Iceland", "name" : "Björk", "aliases" : [ { "name" : "Björk Gudmundsdottir", "sort_name" : "Björk Gudmundsdottir" }, { "name" : "Björk Gudmudsdóttir", "sort_name" : "Björk Gudmudsdóttir" }, { "name" : "Bj rk", "sort_name" : "Bj rk" }, { "name" : "BjÃ¶rk", "sort_name" : "BjÃ¶rk" }, { "name" : "Björk Guðmundsdóttir", "sort_name" : "Björk Guðmundsdóttir" }, { "name" : "Biork", "sort_name" : "Biork" }, { "name" : "Bjõrk", "sort_name" : "Bjõrk" }, { "name" : "Bjørk", "sort_name" : "Bjørk" }, { "name" : "Bjцrk", "sort_name" : "Bjцrk" }, { "name" : "Bjork", "sort_name" : "Bjork" } ], "tags" : [ { "count" : 1, "value" : "soundtrack" }, { "count" : 2, "value" : "ambient" }, { "count" : 1, "value" : "islande" }, { "count" : 1, "value" : "trip-hop" }, { "count" : 1, "value" : "90s" }, { "count" : 1, "value" : "islandais" }, { "count" : 1, "value" : "2000" }, { "count" : 3, "value" : "experimental" }, { "count" : 1, "value" : "dance" }, { "count" : 1, "value" : "idm" }, { "count" : 1, "value" : "rock and indie" }, { "count" : 1, "value" : "10s" }, { "count" : 2, "value" : "alternative" }, { "count" : 7, "value" : "icelandic" }, { "count" : 1, "value" : "multiple ipi" }, { "count" : 1, "value" : "baroque pop" }, { "count" : 2, "value" : "jazz" }, { "count" : 1, "value" : "pop" }, { "count" : 2, "value" : "electronica" }, { "count" : 1, "value" : "00s" }, { "count" : 3, "value" : "electronic" }, { "count" : 3, "value" : "iceland" }, { "count" : 1, "value" : "art pop" }, { "count" : 1, "value" : "progressive pop" }, { "count" : 1, "value" : "a cappella" }, { "count" : 1, "value" : "trip hop" }, { "count" : 1, "value" : "whimsically inclined" } ], "rating" : { "count" : 23, "value" : 84 } }
{ "_id" : ObjectId("5eb62604e78916f7632cc986"), "area" : "United Kingdom", "name" : "The Prodigy", "aliases" : [ { "name" : "Prodigy", "sort_name" : "Prodigy" }, { "name" : "The Prodigy Vs. The Prodigy", "sort_name" : "The Prodigy Vs. The Prodigy" } ], "tags" : [ { "count" : 6, "value" : "big beat" }, { "count" : 1, "value" : "english" }, { "count" : 3, "value" : "british" }, { "count" : 1, "value" : "industrial" }, { "count" : 1, "value" : "dance-punk" }, { "count" : 2, "value" : "uk" }, { "count" : 2, "value" : "breakbeat hardcore" }, { "count" : 1, "value" : "electropunk" }, { "count" : 1, "value" : "britannique" }, { "count" : 1, "value" : "electronica" }, { "count" : 1, "value" : "2005" }, { "count" : 6, "value" : "electronic" }, { "count" : 1, "value" : "dance" }, { "count" : 1, "value" : "alternative rock" }, { "count" : 1, "value" : "dance and electronica" }, { "count" : 1, "value" : "rave" }, { "count" : 2, "value" : "hardcore" }, { "count" : 1, "value" : "rock" }, { "count" : 1, "value" : "breakbeat" }, { "count" : 1, "value" : "electro" }, { "count" : 2, "value" : "techno" } ], "rating" : { "count" : 23, "value" : 90 } }
{ "_id" : ObjectId("5eb62609e78916f7632cf32f"), "area" : "New York", "name" : "Rihanna", "aliases" : [ { "name" : "蕾哈娜", "sort_name" : "蕾哈娜" }, { "name" : "Rhianna", "sort_name" : "Rhianna" }, { "name" : "Riannah", "sort_name" : "Riannah" }, { "name" : "Robyn Rihanna Fenty", "sort_name" : "Fenty, Robyn Rihanna" }, { "name" : "Rihanna", "sort_name" : "Rihanna" } ], "tags" : [ { "count" : 1, "value" : "rnb" }, { "count" : 3, "value" : "barbadian" }, { "count" : 1, "value" : "pop and chart" }, { "count" : 1, "value" : "r&b" }, { "count" : 2, "value" : "dancehall" }, { "count" : 1, "value" : "reggae" }, { "count" : 2, "value" : "hip hop" }, { "count" : 1, "value" : "dance" }, { "count" : 2, "value" : "dance-pop" }, { "count" : 4, "value" : "pop" }, { "count" : 1, "value" : "barbade" }, { "count" : 1, "value" : "barbadien" }, { "count" : 1, "value" : "contemporary r b" }, { "count" : 1, "value" : "barbados" }, { "count" : 1, "value" : "rehab" } ], "rating" : { "count" : 15, "value" : 68 } }
{ "_id" : ObjectId("5eb624dae78916f763218953"), "area" : "United States", "name" : "Britney Spears", "aliases" : [ { "name" : "Bretney Spears", "sort_name" : "Bretney Spears" }, { "name" : "B. Spears", "sort_name" : "B. Spears" }, { "name" : "Brittany Spears", "sort_name" : "Brittany Spears" }, { "name" : "Briteny Spears", "sort_name" : "Briteny Spears" }, { "name" : "Brittney Spears", "sort_name" : "Brittney Spears" }, { "name" : "Britney Jean Spears", "sort_name" : "Spears, Britney Jean" } ], "tags" : [ { "count" : 7, "value" : "pop" }, { "count" : 1, "value" : "américain" }, { "count" : 1, "value" : "electropop" }, { "count" : 1, "value" : "usa" }, { "count" : 1, "value" : "pop and chart" }, { "count" : 1, "value" : "dance-pop" }, { "count" : 1, "value" : "urban pop" }, { "count" : 1, "value" : "if you seek amy" }, { "count" : 1, "value" : "dance" }, { "count" : 2, "value" : "american" } ], "rating" : { "count" : 13, "value" : 83 } }
{ "_id" : ObjectId("5eb62609e78916f7632cfb5c"), "area" : "United States", "name" : "Maroon 5", "aliases" : [ { "name" : "marron 5", "sort_name" : "marron 5" }, { "name" : "マルーン５", "sort_name" : "マルーン５" }, { "name" : "Maroon5", "sort_name" : "Maroon5" } ], "tags" : [ { "count" : 1, "value" : "rock and indie" }, { "count" : 1, "value" : "slow pop" }, { "count" : 1, "value" : "automod ng" }, { "count" : 1, "value" : "pop" }, { "count" : 1, "value" : "rock" }, { "count" : 1, "value" : "dance" }, { "count" : 1, "value" : "pop/rock" }, { "count" : 1, "value" : "fixme label mess" } ], "rating" : { "count" : 11, "value" : 60 } }
{ "_id" : ObjectId("5eb62531e78916f763255ef0"), "area" : "United States", "name" : "Adam Lambert", "aliases" : [ ], "tags" : [ { "count" : 1, "value" : "vocalist" }, { "count" : 1, "value" : "glam" }, { "count" : 1, "value" : "costume" }, { "count" : 1, "value" : "dance" }, { "count" : 1, "value" : "showman" }, { "count" : 1, "value" : "rock" }, { "count" : 1, "value" : "pop" }, { "count" : 1, "value" : "american idol" } ], "rating" : { "count" : 7, "value" : 100 } }
{ "_id" : ObjectId("5eb6258ee78916f76328c7ea"), "area" : "United Kingdom", "name" : "Fatboy Slim", "aliases" : [ { "name" : "ファットボーイ・スリム", "sort_name" : "ファットボーイ・スリム" }, { "name" : "Fatboy Slim - Because We Can", "sort_name" : "Fatboy Slim - Because We Can" }, { "name" : "Fatboy Slin", "sort_name" : "Fatboy Slin" }, { "name" : "Fat Boy Slim", "sort_name" : "Fat Boy Slim" } ], "tags" : [ { "count" : 1, "value" : "trip hop" }, { "count" : 3, "value" : "electronic" }, { "count" : 1, "value" : "dance" }, { "count" : 1, "value" : "trip-hop" }, { "count" : 1, "value" : "english" }, { "count" : 1, "value" : "classic pop and rock" }, { "count" : 2, "value" : "uk" }, { "count" : 2, "value" : "big beat" }, { "count" : 1, "value" : "britannique" }, { "count" : 3, "value" : "british" }, { "count" : 1, "value" : "1998" } ], "rating" : { "count" : 7, "value" : 77 } }
{ "_id" : ObjectId("5eb625b1e78916f7632a1330"), "area" : "United Kingdom", "name" : "Basement Jaxx", "aliases" : [ { "name" : "Basementt Jaxx", "sort_name" : "Basementt Jaxx" }, { "name" : "Basment Jaxx", "sort_name" : "Basment Jaxx" }, { "name" : "Basemant Jaxx", "sort_name" : "Basemant Jaxx" }, { "name" : "Bassment Jaxx", "sort_name" : "Bassment Jaxx" }, { "name" : "Basement Jazz", "sort_name" : "Basement Jazz" }, { "name" : "Basements Jaxx", "sort_name" : "Basements Jaxx" } ], "tags" : [ { "count" : 1, "value" : "english" }, { "count" : 2, "value" : "uk" }, { "count" : 1, "value" : "house" }, { "count" : 1, "value" : "uk garage" }, { "count" : 3, "value" : "dance" }, { "count" : 4, "value" : "british" }, { "count" : 1, "value" : "dance and electronica" }, { "count" : 1, "value" : "10s" }, { "count" : 2, "value" : "electronic" }, { "count" : 1, "value" : "00s" }, { "count" : 1, "value" : "90s" } ], "rating" : { "count" : 6, "value" : 83 } }
{ "_id" : ObjectId("5eb625ace78916f76329e10f"), "area" : "United Kingdom", "name" : "Cornershop", "aliases" : [ { "name" : "Conershop", "sort_name" : "Conershop" }, { "name" : "Corner Shop -", "sort_name" : "Corner Shop -" }, { "name" : "Cornership", "sort_name" : "Cornership" }, { "name" : "Corner Shop", "sort_name" : "Corner Shop" } ], "tags" : [ { "count" : 1, "value" : "dance" }, { "count" : 1, "value" : "indie" }, { "count" : 1, "value" : "brit pop" }, { "count" : 1, "value" : "indian" }, { "count" : 2, "value" : "british" }, { "count" : 1, "value" : "uk" }, { "count" : 1, "value" : "asian" }, { "count" : 1, "value" : "british asian" }, { "count" : 1, "value" : "english" }, { "count" : 1, "value" : "rock and indie" } ], "rating" : { "count" : 5, "value" : 68 } }
'''


